name: Email Form Submission

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        type: string
      email:
        description: 'Email'
        required: true
        type: string
      message:
        description: 'Message'
        required: true
        type: string

jobs:
  send-email:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Debug Inputs
        run: |
          echo "Name: ${{ github.event.inputs.name }}"
          echo "Email: ${{ github.event.inputs.email }}"
          echo "Message: ${{ github.event.inputs.message }}"

      - name: Send Email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: captainveyd@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: captainveyd@gmail.com
          from: ${{ github.event.inputs.email }}
          subject: "New Contact Form Submission from ${{ github.event.inputs.name }}"
          body: |
            Name: ${{ github.event.inputs.name }}
            Email: ${{ github.event.inputs.email }}
            Message: ${{ github.event.inputs.message }}
          content_type: text/plain

      - name: Log Success
        run: echo "Email sent successfully"

      - name: Handle Errors
        if: ${{ failure() }}
        run: |
          echo "::error::Failed to send email"
          echo "::error::Name: ${{ github.event.inputs.name }}"
          echo "::error::Email: ${{ github.event.inputs.email }}"
          echo "::error::Message: ${{ github.event.inputs.message }}"
