name: Email Form Submission

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
        type: string
      email:
        description: 'Email'
        required: true
        type: string
      message:
        description: 'Message'
        required: true
        type: string

jobs:
  send-email:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    steps:
      - name: Debug Inputs
        run: |
          echo "Name: ${{ github.event.inputs.name }}"
          echo "Email: ${{ github.event.inputs.email }}"
          echo "Message: ${{ github.event.inputs.message }}"

      - name: Send Email
        run: |
          echo "Sending email..."
          echo "Name: ${{ github.event.inputs.name }}" > email.txt
          echo "Email: ${{ github.event.inputs.email }}" >> email.txt
          echo "Message: ${{ github.event.inputs.message }}" >> email.txt
          
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            --data '{"event_type": "email_submission", "client_payload": {"name": "${{ github.event.inputs.name }}", "email": "${{ github.event.inputs.email }}", "message": "${{ github.event.inputs.message }}"}}' \
            https://api.github.com/repos/veydk/personal-website/dispatches

      - name: Log Success
        run: echo "Email sent successfully"

      - name: Handle Errors
        if: ${{ failure() }}
        run: |
          echo "::error::Failed to send email"
          echo "::error::Name: ${{ github.event.inputs.name }}"
          echo "::error::Email: ${{ github.event.inputs.email }}"
          echo "::error::Message: ${{ github.event.inputs.message }}"
